### PR TITLE
multi-platform/version build

### PR DESCRIPTION
**Pull request by dcwhite**
Still have "ok to error" turned on. 

This time just MacOS 10.15/py3.6 failed:
```
>       self.assertAlmostEqual(qerr, 0, delta=delta, msg=msg)
E       AssertionError: 0.015258386895701595 != 0 within 0.01 delta : Failed for (M, alpha, beta)=(14, 1.353544, 1.541622)

tests/test_pce.py:58: AssertionError
```

### CODE REVIEW

**Comment by akilnarayan** [comment]
That error is still just a random thing. I pushed tolerance loosening again. Let's see if it works this time.

**Comment by dcwhite** [comment]
It passed this time, I'll try turning the tests "on" (in terms of fail => error)

**Comment by dcwhite** [comment]
```
 >           self.assertAlmostEqual(np.linalg.norm(x0-x1,ord=np.inf), 0., delta=delta, msg=errstr)
E           AssertionError: 0.009052601517883785 != 0.0 within 0.005 delta (0.009052601517883785 difference) : Failed for alpha=6.392, beta=4.225, n=0, u=0.997349

tests/test_jacobipolys.py:119: AssertionError
```

**Comment by dcwhite** [comment]
@akilnarayan Still have this random error. Is this the same one @ZEXINLIU is working on?
```
        J = JacobiPolynomials(alpha=alpha,beta=beta)
    
        delta = 5e-3
        for n in range(nmax)[::-1]:
            x0 = J.idistinv(u, n)
            x1 = J.fidistinv(u, n)
    
            ind = np.where(np.abs(x0-x1) > delta)[:2][0]
            if ind.size > 0:
                errstr = 'Failed for alpha={0:1.3f}, beta={1:1.3f}, n={2:d}, u={3:1.6f}'.format(alpha, beta, n, u[ind[0]])
            else:
                errstr = ''
    
>           self.assertAlmostEqual(np.linalg.norm(x0-x1,ord=np.inf), 0., delta=delta, msg=errstr)
E           AssertionError: 0.0066981028220215455 != 0.0 within 0.005 delta (0.0066981028220215455 difference) : Failed for alpha=8.638, beta=4.313, n=1, u=0.997952

tests\test_jacobipolys.py:119: AssertionError
```

**Comment by ZEXINLIU** [comment]
> @akilnarayan Still have this random error. Is this the same one @ZEXINLIU is working on?
> 
> ```
>         J = JacobiPolynomials(alpha=alpha,beta=beta)
>     
>         delta = 5e-3
>         for n in range(nmax)[::-1]:
>             x0 = J.idistinv(u, n)
>             x1 = J.fidistinv(u, n)
>     
>             ind = np.where(np.abs(x0-x1) > delta)[:2][0]
>             if ind.size > 0:
>                 errstr = 'Failed for alpha={0:1.3f}, beta={1:1.3f}, n={2:d}, u={3:1.6f}'.format(alpha, beta, n, u[ind[0]])
>             else:
>                 errstr = ''
>     
> >           self.assertAlmostEqual(np.linalg.norm(x0-x1,ord=np.inf), 0., delta=delta, msg=errstr)
> E           AssertionError: 0.0066981028220215455 != 0.0 within 0.005 delta (0.0066981028220215455 difference) : Failed for alpha=8.638, beta=4.313, n=1, u=0.997952
> 
> tests\test_jacobipolys.py:119: AssertionError
> ```
Yes, it's exactly what I'm working on. Thanks for the notice, Dan.

**Comment by dcwhite** [comment]
Cool. Let's get this merged, with the tests set to "run but not fail the build." When the failure is fixed, you can enable the test-failure toggle as part of your PR and to run the "tri-tri-build"

**Comment by akilnarayan** [comment]
Sounds good, thanks Dan.

**Pull request merged**
