### PR TITLE
Rtd init

### PR DESCRIPTION
**Pull request by jessdtate**
initial Read the docs page

### CODE REVIEW

**Comment by jessdtate** [comment]
Please test the build instructions in this branch.  They can be found in the preview (https://uncertainsci--66.org.readthedocs.build/en/66/dev_docs/HowToTutorial.html#testing-documentation).  I still have some things to clean up before it is merged.

**Comment by jessdtate** [comment]
I think this is ready to go in, assuming that it passes review.

**Review by akilnarayan — APPROVED** [review]
I'm approving, don't know if it's worth waiting for at least one other person to give a thumbs-up

**Review by dcwhite — APPROVED** [review]
Will https://sciinstitute.github.io/UncertainSCI/ go away or be replaced with the RTD one? Let me know so i can adjust the repo setting

**Comment by jessdtate** [comment]
Yeah, It seems foolish to keep both RTD and github pages.

**Pull request merged**
