### PR TITLE
Add skeleton documentation site

### PR DESCRIPTION
**Pull request by nids2001**

### CODE REVIEW

**Comment by dcwhite** [comment]
We'll merge this and try generating the page from docs. I'm not sure how else to test a new page.

**Comment by dcwhite** [comment]
@nids2001 We can test this if you turn on github pages from docs in the settings on your fork. Can you do that and post a link to the generated page? Thanks

**Comment by dcwhite** [comment]
It's in Settings->Options->scroll down to Github Pages settings.

**Comment by nids2001** [comment]
[https://nids2001.github.io/UncertainSCI/](https://nids2001.github.io/UncertainSCI/)

**Comment by dcwhite** [comment]
Thanks!

**Pull request merged**
