### PR TITLE
Initial structure for documentation

### PR DESCRIPTION
**Pull request by akilnarayan**
@dcwhite @jessdtate I restructured the source into an UncertainSCI subdir. Does this break anything in the egg or in setup.py?

### CODE REVIEW

**Comment by dcwhite** [comment]
Probably, I can test next week when I’m back from staycation.

**Comment by dcwhite** [comment]
Shoot. We have two conflicting /docs/ PRs. Github pages uses that folder to generate a webpage; I suppose sphinx files can also live there, and "cooperate" with the web page content, ideally. The question is, which should we merge first? There's also the probably-breaking unit test PR. We could just merge all 3 in and sort it out later; or merge pairs of them into test branches and see which is least messed-up. Thoughts? @jessdtate @akilnarayan

**Comment by akilnarayan** [comment]
I think maybe merging this and the other docs request is probably fine. I took at cursory look at the docs dirs and they seem to have orthogonal content. I think the unit test PR is different so maybe we should do that separately? Maybe merge the two docs first into master, then update the unit test PR branch with those changes?

Anyway, this PR seems to be ok for now, so I'll un-draft it.

**Comment by dcwhite** [comment]
OK good plan. We'll go #48->#49->#46.

**Pull request merged**
