### PR TITLE
Create pythonapp.yml

### PR DESCRIPTION
**Pull request by dcwhite**
I just took the basic Python build template from Github. It uses pip and a requirements file, then runs test using Pytest.

### CODE REVIEW

**Comment by dcwhite** [comment]
It won't work until those requirements are laid out.

**Comment by akilnarayan** [comment]
I just pushed an update to requirements.txt that hopefully fixes it. Let me know

**Comment by dcwhite** [comment]
Now it's a different error, which looks to be more technical. I will investigate more.

**Comment by akilnarayan** [comment]
Ok. I did try a local `pip install requirements` and it seemed to work fine, so I don't know what the issue is

**Comment by dcwhite** [comment]
Observations:
* The numpy version 1.17.0 is old enough to be marked "legacy" so pip tries to build it from scratch rather than just grab a wheel.
* 1.18.0 has a wheel available, is that version too new?
* 1.17.1 has the same error as 1.17.0
* 1.17.2 still does not have a wheel, but the build works. Switch to this one OK?

**Comment by akilnarayan** [comment]
- 1.18.0 is fine. That's not a problem
- 1.17.2 is also ok

I've tested on 1.18.1, and it works fine. Was the problem on 1.17.0 or 1.17.1 apparent?

**Comment by dcwhite** [comment]
Nasty build error, it seems like there are a lot of missing underlying numerical libraries on these action VMs:
```command: /opt/hostedtoolcache/Python/3.8.3/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3qbeu_q9/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3qbeu_q9/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-frpryqxu/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hostedtoolcache/Python/3.8.3/x64/include/python3.8/numpy
         cwd: /tmp/pip-install-3qbeu_q9/numpy/```

Lots of these:
```  libraries openblas not found in ['/opt/hostedtoolcache/Python/3.8.3/x64/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE```

So it's probably Github's fault, as far as supporting the combo 3.8.3/1.17.0...probably something I can't fix. Bumping our version number will surely be easier.

**Comment by dcwhite** [comment]
I can go with 1.17.2.

Now this thing is running a linter, and it's finding a few test code issues:

```
Successfully installed flake8-3.8.3 mccabe-0.6.1 pycodestyle-2.6.0 pyflakes-2.2.0
./opolynd.py:197:35: F821 undefined name 'j'
        ax.plot_surface(X, Y, p[:,j].reshape(N,N), cmap=cm.coolwarm, linewidth=0,antialiased=True)
                                  ^
./opoly1d.py:754:20: F821 undefined name 'a'
        assert n < a.size
                   ^
./opoly1d.py:755:20: F821 undefined name 'b'
        assert n < b.size
                   ^
3     F821 undefined name 'a'
```

**Comment by akilnarayan** [comment]
Ok, I pushed something that should fix those code issues.

**Comment by dcwhite** [comment]
Super! Let's see if the build's green now...

**Comment by dcwhite** [comment]
Looks like more setup is needed for generalized running of unit tests: https://docs.pytest.org/en/latest/goodpractices.html

**Comment by dcwhite** [comment]
@akilnarayan Would you be OK if I made the build pass by ignoring the unit test error, so we can get a semi-functioning CI script in master, then I can work on the unit test config part in a new branch?

**Comment by akilnarayan** [comment]
Sure, I'm fine with that

**Comment by dcwhite** [comment]
@jessdtate @akilnarayan We've decided to get the first version of this in master while I work on the unit test part. That way, other PRs can benefit from the linting part.

**Pull request merged**
